services:
  deps:
    image: node
    volumes:
      - ".:/app"
      - "node_modules:/app/node_modules"
    working_dir: /app
    command:
      - npm
      - install
    profiles:
      - run
  app:
    image: node
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "node_modules:/app/node_modules"
    working_dir: /app
    depends_on:
      - mongodb
    command:
      - ./wait-for-it.sh
      - "mongodb:27017"
      - "--"
      - npm
      - run
      - dev
    environment:
      MONGODB_URL: "mongodb://admin:root@mongodb:27017"
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - "data:/data/db"
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: "mongodb://admin:root@mongodb:27017"
volumes:
  data: null
  node_modules: null
